Repository 0x61nas/aarty, pull requests merged in 2022-10, with the labels that each got.

#3 Fixed typo error in installation instruction
  README.md
Labels: hacktoberfest-accepted

#5 Modular output methods
  src/args.rs
  src/ascii_processor.rs
  src/main.rs
  src/output.rs
Labels: enhancement, hacktoberfest-accepted

#6 Feature: `width` argument to calculate scale from number of available columns
  README.md
  src/args.rs
  src/ascii_processor.rs
Labels: enhancement
